name: Build FreeSwitch main docker image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'main/**/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup .NET Core ${{ env.DotNetVersion }}
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: ${{ env.DotNetVersion }}

      - name: Determine semantic version
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
          
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: main/Dockerfile
          build-args: |
            version=${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}.${{steps.nbgv.outputs.BuildNumber}}${{steps.nbgv.outputs.PrereleaseVersion}}
          tags: |
            ghcr.io/exram/freeswitch:${{steps.nbgv.outputs.VersionMajor}}
            ghcr.io/exram/freeswitch:${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}
            ghcr.io/exram/freeswitch:${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}.${{steps.nbgv.outputs.BuildNumber}}
            ghcr.io/exram/freeswitch:${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}.${{steps.nbgv.outputs.BuildNumber}}${{steps.nbgv.outputs.PrereleaseVersion}}
            ghcr.io/exram/freeswitch:${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}.${{steps.nbgv.outputs.BuildNumber}}${{steps.nbgv.outputs.PrereleaseVersion}}.${{steps.nbgv.outputs.VersionHeight}}
